config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  get "offers", to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to:"users#new"
  
  resources :users, only:[:create]
  resources :offers, only:[:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :offer_content, presence: true, length: {maximum: 255}
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :staff,inclusion: [true,false]
  has_secure_password
  
  has_many :offers, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  private
  # ログイン要求
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def create
  #   @comment = login_user.comments.build(comment_params)
  #   if @comment.save
  #     redirect_to "users/show"
  #   else
  #     redirect_to "users/show"
  #   end
  # end
  
  # private
  
  # def comment_params
  #   params.require(:comment).permit(:comment_content, :offer_id)
  # end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @offers = login_user.offers.build(offer_params)
    if @offers.save
      flash[:success] = "タクシーを依頼しました。到着までしばらくお待ち下さい。"
      redirect_to root_url
    else
      @pagy, @offers = pagy(login_user.offers.order(id: :desc))
      flash[:danger] = "メッセージが送信できませんでした。"
      # render "toppages/index"
      redirect_to root_url
    end
  end
  
  private
  
  def offer_params
    params.require(:offer).permit(:offer_content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @offer = login_user.offers.build
      
      @pagy, @offers = pagy(login_user.offers.order(id: :desc))
    end
    @users_offer = Offer.all.order(id: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_user_logged_in, only: [:index, :show]
  
  # def show
  #   @user = User.find(params[:id])
  #   @pagy, @offers = pagy(login_user.offers.order(id: :desc),item: 5)
  # end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ご登録ありがとうございます！登録が完了致しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "登録に失敗しました。入力内容に誤りがないかご確認下さい。"
      render :new
    end
  end
  
  private
  # ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :staff)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login_user
    @login_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!login_user
  end
end

app/views/layouts/_error_messages.html.erb
<!--エラーメッセージ-->
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<!--フラッシュメッセージ-->
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<!--ナビバー-->
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">タクシーコール</a>
      <span class="text-light w-100">簡単操作でタクシーを依頼できるサービスです</span>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <%if logged_in? %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %></li>
          </ul>
        <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "新規登録", signup_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaxiCall</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= render "layouts/flash_messages" %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/offers/_offers.html.erb
<% if offers.any? %>
  <ul class="list-unstyled mt-2">
    <% offers.each do |offer| %>
    <li class="d-flex">
      <div>
        <%= link_to offer.user.name, user_path(offer.user), class: "text-decoration-none" %><span class="text-muted">投稿日時<%= offer.created_at %></span>
      </div>
      <div>
        <p><%= offer.offer_content %></p>
      </div>
    </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/toppages/_offer_log.html.erb
<!--配車履歴パーシャル-->
  <% if offers.any? %>
    <% offers.each do |offer| %>
      <span><%= offer.user.name %> 様から <%= offer.created_at %> にメッセージが送られてきました。</span>
      <p>配車希望場所 : <%= offer.offer_content %></p>
    <% end %>
    <%== pagy_bootstrap_nav(@pagy) %>
  <% end %>

app/views/toppages/index.html.erb
<!--トップページ-->
<!--ログイン完了時に表示-->
<% if logged_in? %>
  <!--true の処理ユーザー側-->
  <% if login_user.staff? %>
    <div class="text-center">
      <h1>ユーザー側 :<%= login_user.name %></h1>
      
      <div class="row">
        <aside class="col-sm-5">
        <h2>タクシーを依頼する</h2>
          <%= form_with(model: @offer) do |f| %>
            <%= f.text_area :offer_content, class: "form-control", placeholder: "タクシーをご希望される場所、施設名をご記入ください" %>
            <%= f.submit "タクシーをお願いする", class:"btn btn-primary w-100" %>
          <% end %>
        </aside>
        <div class="col-sm-7">
          <h2>配車履歴</h2>
          <%= render "toppages/offer_log", offers: @offers %>
        </div>
      </div>
    </div>
  <!--false の処理ドライバー側-->
  <% else %>
    <div class="text-center">
      <h1>タクシー側 :<%= login_user.name %></h1>
      
      <div class="row">
        <aside class="col-sm-5">
        <h2>お客様へメッセージを送信する</h2>
          <%= form_with(model: @offer) do |f| %>
            <%= f.text_area :offer_content, class: "form-control", placeholder: "例:~時頃到着予定です。" %>
            <%= f.submit "送信", class:"btn btn-primary w-100" %>
          <% end %>
        </aside>
        <div class="col-sm-7">
          <h2>依頼履歴</h2>
          <%= render "toppages/offer_log", offers: @users_offer %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
<!--未ログイン時に表示-->
  <div class="text-center">
    <h1>ようこそ！タクシーコールへ！</h1>
    <h2><%= link_to "ログイン", login_path %></h2>
    <p>登録がお済みで無い方は<%= link_to "こちら", signup_path %></p>
  </div>
<% end %>

app/views/users/new.html.erb
<!--会員登録ページ-->
<div class="text-center">
  <h1>新規会員登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="mb-3">
        <%= f.label :name, "お名前" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="mb-3">
        <%= f.label :emal, "メールアドレス" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      
      <div class="mb-3">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      
      <div class="mb-3">
        <%= f.label :password_confirmation, "パスワード確認" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      
      <!--チェックされている時true 一般のお客様-->
      <%= f.label :staff, "一般のお客様はチェックをお願いします。" %>
      <%= f.check_box :staff, {}, "true", "false" %>
      
      <%= f.submit "登録する", class:"btn btn-primary w-100" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--ユーザーページ-->
<% if login_user.staff? %>
<!--true の処理ユーザー側-->
<div class="row">
  <div class="text-center">
    <h1>ようこそ！<%= @user.name %>さん！</h1>
  </div>
<% else %>
<!--false の処理ドライバー側-->
  <div class="text-center">
    <h1>ようこそ！<%= @user.name %>さん！</h1>
  </div>
<% end %>
<%= render "offers/offers", offers: @offers %>
</div>